### ISSUE TITLE
Overlay makes two images unequal; Or, the tragedy of transitive property of equality

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#116] opened 2016-08-21 05:22 UTC
```
> include image
> X = 50
> a = square(X, "solid", name-to-color("blue"))
> b = overlay(a, empty-scene(X, X))
> c = overlay(a, a)
> b == a
true
> a == c
true
> b == c
false
```

The problem is likely because of https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/trove/image-lib.js#L1126

**Comment by schanzer** [comment] 2016-08-21 12:57
Looks like an older version of the WeScheme equality check code. Will port this forward.

**Comment by schanzer** [comment] 2016-08-21 20:15
Confirmed fixed by https://github.com/brownplt/code.pyret.org/commit/f4a3f2b0fe25708c50edecef4c3ded9f488f9f9a

**Comment by schanzer** [comment] 2016-09-06 17:16
@sorawee - do you still see this issue?

**Comment by schanzer** [comment] 2017-02-08 13:16
Is there any way to verify whether or not this code is present on horizon? I'm still seeing the old behavior, but that could be that it still hasn't been updated.

**Comment by jpolitz** [comment] 2017-02-08 14:37
It's fixed on horizon, just checked.  (https://pyret-horizon.herokuapp.com/editor#share=0B32bNEogmncOeUpCTDlfMXBHOG8)

**Closed** 2017-09-22 15:12 UTC
Labels: horizon-fixed
