### ISSUE TITLE
dark mode for CPO

### ISSUE THREAD

**Issue by shriram** [brownplt/code.pyret.org#312] opened 2019-07-26 17:46 UTC
We can get a dark mode by messing with CSS settings, but most people don't know how to do that. It'd be nice if CPO had a dark mode menu entry. This seems especially valuable for visual impairment accessibility.

**Comment by blerner** [comment] 2020-06-14 17:23
Dupe of #329; that one now has more comments.

**Closed by blerner** 2020-06-14 17:23 UTC
