### ISSUE TITLE
modes should work for categorical data

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#510] opened 2024-02-15 18:45 UTC
In the Statistics package, modes throws an internal error when used with non-numeric data. At the very least, this should be a better error! But more importantly, modes are not restricted to numbers. (This has some implications for our treatment of the topic in Bootstrap:DS -- right now we give a falsely narrow definition simply because Pyret doesn't support the full definition)

**Comment by asolove** [comment] 2024-03-12 23:14
Started looking at this one, some notes so I don't forget when I come back to this:

- The resolution of this will need to be over in `pyret-lang`, which defines the [statistics package](https://github.com/brownplt/pyret-lang/blob/ed1daeb75f7af2a07a890b26def99c07186b1acd/src/arr/trove/statistics.arr#L7).

- The interesting bit here is that the definitions are currently typed for numbers and the implementations depend on that for efficiency, so we'll need to:
  - Convert all these methods to be generic or just add a second set of parallel methods for strings. (Do we want to allow over arbitrary types? I don't think Pyret has a notion of generic constraints, and we'd like to constrain this to things where equality is reasonable. I also don't think we want arbitrary mixed types.)
  - convert the implementation of [`group-and-count`](https://github.com/brownplt/pyret-lang/blob/ed1daeb75f7af2a07a890b26def99c07186b1acd/src/arr/trove/statistics.arr#L53), which currently depends on the runtime helper [`raw_array_sort_nums`](https://github.com/brownplt/pyret-lang/blob/ed1daeb75f7af2a07a890b26def99c07186b1acd/src/js/base/runtime.js#L4214) to an alternative that will work for other types. (We probably still want to use the fast version for numbers, though?)

**Comment by asolove** [comment] 2024-03-12 23:18
Related discussion over in pyret-lang, mostly around actually enforcing the type constraint and showing a nicer error, rather than extending these to other types: https://github.com/brownplt/pyret-lang/issues/1538

**Comment by schanzer** [comment] 2024-03-13 00:36
@asolove oh wow - really interesting to see that thread. I didn't realize this came up 2 years ago! In that case, maybe the solution is just a written-in-pyret-function that lives in our Data Science library. Would you be willing to write one?

**Comment by asolove** [comment] 2024-03-13 00:49
Yeah, we could definitely do that. Can you point me to the Data Science library?

**Comment by schanzer** [comment] 2024-03-13 00:53
[Here's the link](https://code.pyret.org/editor#share=10xjKNWI5k4kquuyAls91zaY2TxeX4taz&v=0c33ff0) - I'm sure I'm not doing the most elegant stuff, so any advice you have on coding quality is most welcome!

**Comment by asolove** [comment] 2024-03-14 01:36
Gonna close this out as the resolution won't be in the CPO codebase. But it's still on my backlog list so I'll write some suggested changes to that file and share with you.

**Comment by blerner** [comment] 2024-05-02 13:45
Closing this as dupe of https://github.com/brownplt/pyret-lang/issues/1538, since the discussion there is further along.

**Closed as completed by blerner** 2024-05-02 13:45 UTC
