### ISSUE TITLE
Different URLs make two images unequal

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#115] opened 2016-08-21 05:03 UTC
```
> I.image-url("https://cloud.githubusercontent.com/assets/9099577/17835446/7397451c-6721-11e6-9a31-e4e2ee1043a2.gif") == I.image-url("https://cloud.githubusercontent.com/assets/9099577/17835447/78ccdff6-6721-11e6-810d-8637dd1f2c80.gif")
false
```

despite the fact that both images have the same file content.

The problem is likely from https://github.com/brownplt/code.pyret.org/blob/master/src/web/js/trove/image-lib.js#L929

**Comment by schanzer** [comment] 2016-08-21 12:57
Looks like an older version of the WeScheme equality check code. Will port this forward.

**Comment by schanzer** [comment] 2016-08-21 20:09
Confirmed fixed by https://github.com/brownplt/code.pyret.org/commit/55cbf7fbd42ea17487a0d093da33c8c4d0245003

**Closed** 2016-09-06 17:18 UTC
