### ISSUE TITLE
Code-folding confused by object literals

### ISSUE THREAD

**Issue by jswrenn** [brownplt/code.pyret.org#119] opened 2016-08-26 16:58 UTC
![object literal with no fields, with several lines between the open and close brackets](https://cloud.githubusercontent.com/assets/3820879/18013536/7e0662de-6b8c-11e6-9147-46e9c1818413.png)

**Comment by belph** [comment] 2017-07-01 15:57
This must be fixed, since I am unable to reproduce it on horizon. Closing.

**Comment by blerner** [comment] 2017-07-01 16:00
Nope, it's still a problem for me in Firefox, on CPO#horizon.

**Comment by belph** [comment] 2017-07-01 16:30
Ah, I figured it out! Edge cases are fun. Fixed.

**Closed** 2017-07-01 16:30 UTC
Labels: bug, horizon-fixed
