### ISSUE TITLE
Methods for viewing the state of a running big bang may be unsatisfactory

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#74] opened 2016-05-25 01:52 UTC

**Comment by blerner** [comment] 2016-05-25 01:55
See, honestly, this horrifies me.  The big-bang window draws pictures.  It's a visual type error for it to have a rich value rendering there.  It encourages students to have `to-draw` methods that then produce whatever the heck they want, because "the big-bang window will draw anything for me"

**Comment by schanzer** [comment] 2016-05-25 01:57
I know you and @jpolitz have discussed moving state output elsewhere, and I'm cool with that. But wherever it winds up, tables should be printed if they represent the state of the world

**Comment by sorawee** [comment] 2016-05-25 01:59
Agree with Ben. I still think that to-draw should not be optional.

By the way, I recall that Shriram who thinks that to-draw should be optional said that without to-draw, the value should be printed to the REPL instead.

**Comment by jpolitz** [comment] 2016-05-25 02:01
This discussion about where value rendering goes is pretty off-topic for this issue, though, right?  Clearly the issue is pointing out (perhaps unsurprisingly) that in the prototype, there's a spot where value rendering isn't considering tables.  That suggests there's an issue no matter where that rendering code goes.

**Comment by schanzer** [comment] 2016-05-25 02:04
Exactly - "wherever it winds up, tables should be printed if they represent the state of the world".

**Comment by blerner** [comment] 2016-05-25 02:12
If I run the code above, nothing gets rendered in the window, and when I close the window, the final world value doesn't get output.  That's not a surprise, given that currently we don't print any top-level values in definitions areas.  If I let-bind `ans = big-bang(...)` and then ask for `ans` in the REPL, I get a pretty table.

Joe has a TODO mark in the world.js implementation about what to do when the `to-draw` function doesn't return an image, and the code seems to have bit-rotted at the moment.  The rendering isn't "not considering tables" -- it's not considering anything that isn't an image (and rightly so in my opinion!)

The only way I'd see a clearer path through this is if we get rid of `to-draw` entirely, and rename it `render`, which is completely agnostic to types.  Sure, you'll have horrid performance problems `torepr`ing arbitrary data each tick (because large HTML subtrees are expensive to create, and is why we cache the canvas between frames of a normal animation), but that seems to be the behavior you're arguing for right now...

**Comment by jpolitz** [comment] 2016-05-25 02:14
Cool, made an issue for it: https://github.com/brownplt/code.pyret.org/issues/75

**Comment by schanzer** [comment] 2016-05-25 02:25
I think we all agree that `to-draw` should require an image-producing function. But there's a pedagogical win to (optionally) allow a user to see the state of the World in some form, and I can't imagine a good reason to show the state if it's a list or a struct, but not if it's a table. Being able to see the state of the world was a game-changer when we added it to WeScheme, and @jpolitz saw the same benefit in the BS:2 workshop last year.

**Comment by shriram** [comment] 2016-05-25 02:28
But that can't be `to-draw`. It'd have to be something else, including no
"renderer" at all.

**Comment by schanzer** [comment] 2016-05-25 02:30
Racket has the `(show-state true)` handler, which is super-awkward. Personally, I always thought Danny's solution was really elegant.

**Comment by schanzer** [comment] 2016-05-25 03:10
Here's why I'd like to see `to-draw` be optional:
When introducing `big-bang`, it's effective to have students build up their understanding by acting out one handler at a time. It's really useful to have student create a counter as quickly as possible, and `(big-bang 0 (on-tick add1))` was always great in a pinch. Forcing students to write an `on-tick` _and_ `to-draw` handler just to see a counter seems like a heavy lift, and `big-bang` is already pretty darned heavy.

**Comment by shriram** [comment] 2016-05-25 12:44
And I can see this being really useful in the physics/modeling case, too.
You run your most basic simulation with an initial value and updater
function and see values flashing by; then you add an on-tick to slow it
down; then maybe a stop-when to halt it.

In fact, what would be ideal then is if it were possible to get all the
simulated values (i.e., sequence of world values) out of it into a data
structure (ahem, table), and send that off to the graphing library. That
could be really awesome for physics/modeling.

**Comment by schanzer** [comment] 2016-05-25 12:54
*jaw drop*

**Comment by shriram** [comment] 2017-06-18 21:04
Correct. I'm going to go ahead and close it. If @schanzer wants to keep this open, I suggest a new problem posting that frames it _in terms of_ what we now have with reactors and inspecting their intermediate state, rather than prolonging a discussion based on a former version of the language. @kfisler You can ignore this.

**Closed by shriram** 2017-06-18 21:04 UTC
