### ISSUE TITLE
Footer overlap with coding pane when zoomed in

### ISSUE THREAD

**Issue by P-bibs** [brownplt/code.pyret.org#318] opened 2019-11-07 01:19 UTC
When zoomed in on CPO, the welcome footer overlaps with the last line of the coding window when scrolled all the way down. This can be seen below: 

![Screenshot from 2019-11-06 20-05-41](https://user-images.githubusercontent.com/40366824/68351697-3b862280-00d2-11ea-9b57-155a84dbd92c.png)

Notice that the bottom of line 162 is cut off, even though the window is scrolled all the way down. This is a hindrance for users on high DPI screens or projectors who routinely are zoomed in while using the website.

A simple solution may be to decrease the height of the footer to `2em` instead of `2.5em`, but a more elegant fix may make more sense.

**Comment by jpolitz** [comment] 2019-11-15 16:43
Thanks for reporting this. I've been poking at this and I'm pretty confused. The `.replMain` class has `padding-bottom` set to `2.5em`, which is also the height of `#footer`. As far as I can tell they are siblings and both have `font-size: 100%` and `font: inherit`. Yet the footer's calculated height is 40px (with margin, padding, border = 0) and the definitions area's calculated padding-bottom is 30px. This seems to persist across at least Brave, Chrome, and Safari so I'm sure it's something wrong with our CSS and not with the CSS implementations. Maybe @blerner can tell me why my model of CSS is all wrong here.

**Comment by blerner** [comment] 2019-11-15 23:56
I can reproduce this without being zoomed in, on Firefox/Linux at least.  https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/css/editor.css#L536 sets `font-size` to 12px for `#main`, so 2.5em = 30px, but the footer inherits the default font size of the browser, which for me on Linux is 16px (set in browser options, not anywhere in our own CSS), so 2.5em = 40px for the footer.

**Comment by P-bibs** [comment] 2019-11-16 04:16
Just to provide more information, I originally noticed the bug on a 2560x1440 display on 200% zoom and it persisted on Chrome across both Linux and Windows. However, I couldn't manage to reproduce it when zoomed out.
Regardless, it seems like you've figured it out. It's interesting stuff and a valuable lesson: I definitely won't be haphazard about what CSS units I use in the future.

**Comment by blerner** [comment] 2019-11-16 11:43
Very strangely, on Firefox/Windows and Chrome/Windows, the relevant CSS rule says `.replMain { padding-bottom: 2.5rem; }`, where `rem` means "root ems", so it matches the font size of the footer.  I cannot figure out where the heck that `rem` line is appearing in the CSS, though!

Regardless, the correct fix is to explicitly specify the font-size for the `#footer` as well as for `#main`

**Comment by schanzer** [comment] 2020-05-04 22:00
I'm not able to reproduce this on FF (latest) on OSX. Am I missing something?

**Comment by blerner** [comment] 2020-08-13 04:08
No, I think I fixed this in https://github.com/brownplt/code.pyret.org/commit/09f57aaf7980af1f6937bdadceb1f1920ae8a497, and it appears to be merged now.

**Closed by blerner** 2020-08-13 04:08 UTC
