### ISSUE TITLE
Generic errors have bad wrapping

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#286] opened 2018-08-08 21:02 UTC
I'm starting to thread reasonable error-checking through the DS library, but generic errors don't wrap. This results in the following nightmare:

![image](https://user-images.githubusercontent.com/77126/43864135-d9807844-9b2c-11e8-906e-afa5495c17bf.png)

**Comment by blerner** [comment] 2018-08-08 21:08
Ooh, interesting!  Two things:
1) This is a comment about generic message exceptions (i.e. `throwMessageException` or similar) -- In general, we render those the same as if we're rendering any Pyret string.  The fact that the error UI doesn't wrap here is unfortunate, but it's understandable, since Pyret strings don't automatically wrap.
2) We shouldn't be using `throwMessageException` so often!

**Comment by schanzer** [comment] 2018-08-08 21:16
I see the importance of not wrapping-by-default (esp in the presence of multi-line strings!), but I'm not clear on why we wouldn't want exceptions to wrap.

Is there a way to have user-generated exceptions handled differently, or to have their error strings treated differently from string values that are printed out in the REPL?

**Comment by jpolitz** [comment] 2018-08-08 21:57
Yeah we should fix this format. Thanks for seeing the content again; I thought this was fixed a while ago with https://github.com/brownplt/code.pyret.org/issues/156

**Comment by blerner** [comment] 2018-08-09 00:45
One possibility is to modify https://github.com/brownplt/pyret-lang/blob/horizon/src/arr/trove/error.arr#L2407-L2414, so that if the value being thrown is an `ErrorDisplay`, we simply use that value as the rendered error.  For example,
```
import error-display as ED
include error

fun foo(x):
  raise([ED.error: [ED.para: ED.code(ED.text("foo")), ED.text(" failed with ")],
      [ED.para: ED.embed(x)]])
end

foo([list: 1, 2, 3])
```
renders as
![image](https://user-images.githubusercontent.com/918464/43871709-e1ad293a-9b4b-11e8-9959-f3dda715e316.png)
![image](https://user-images.githubusercontent.com/918464/43871723-f032b7f4-9b4b-11e8-8093-2166b93002eb.png)

The stack trace is one level too detailed, but other than that, it's pretty good...

**Comment by blerner** [comment] 2020-08-13 04:11
Dupe of #334 , but both have good discussion

**Closed by blerner** 2020-08-13 04:11 UTC
